### ISSUE TITLE
Dependency on lodash on purpose?

### ISSUE THREAD

**Issue by houmark** [apostrophecms/apostrophe-signup#1]
https://github.com/apostrophecms/apostrophe-signup/blob/7a7fc43bba43c6257cd97806fc68ccd53ca9f6ae/index.js#L2

Maybe not so important or it's on purpose, but all of Apostrophe core depends on the sails lodash fork, should this one also do that or?

**Comment by boutell** [comment]
Nope. Only existing modules that could be destabilized by the change.
