### ISSUE TITLE
Error on clean install

### ISSUE THREAD

**Issue by StuBramley** [apostrophecms/apostrophe-signup#2]
Installed apostrophe-signup, cut and pasted app.js configuration - but crashed immediately with the following error:  

node_modules/apostrophe-signup/index.js:27
      self.apos.users.addSecret('signupConfirm');
                      ^

TypeError: self.apos.users.addSecret is not a function

**Comment by boutell** [comment]
Your `apostrophe` module is out of date, `npm update`.
