### ISSUE TITLE
How to redirect user to confirm email page if email sending failed

### ISSUE THREAD

**Issue by sushanpth** [apostrophecms/apostrophe-signup#9]
Hi,

How can I change the default behaviour of showing same error message for duplicate email and verification email send failed. 

The error message `That username or email address may be in use. Please review and try again.` is confusing. 

If email sending fails I want to redirect user to confirm email page where user can input email and can receive confirmation email again.

**Comment by abea** [comment]
That is in the `signup.html` template file. You would then also need to override `user.js` where it shows `'.apos-signup-error'`.
